
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:6006/REL?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: true